name: Build SBOM and se
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2    
      - name: Install syft
        run: |
          LATEST_SYFT_VERSION=$(curl -s https://api.github.com/repos/anchore/syft/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin "$LATEST_SYFT_VERSION"
          syft version
      - name: Generate SBOM
        run: syft ./ -o cyclonedx-json >sbom.json
 

      - name: Save Sbom to new file 
        run: |    
           echo -n "$(cat './sbom.json')" | jq '. + {"name": "${{github.actor}}"}' | jq '. + {"repo": "${{github.repositoryUrl}}"}' > sbom_file.json 
      - name: Call Api
        run: |  
          curl -k --request POST 'https://dt.cryptosoft.com:9443/api/v1/guest/sbom-github' \
          --header 'Content-Type: application/json' \
          --data  @sbom_file.json 
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: ./sbom_file.json 
